version: "3.2"
services:
  php:
    build: "./docker/php/"
    networks:
      - test-node-finder
    volumes:
      - ./app/:/var/www/html/
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_USER=${MYSQL_USER:-admin}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-node-finder}
  apache:
    build: "./docker/apache/"
    depends_on:
      - php
      - mysql
    networks:
      - test-node-finder
    ports:
      - "8080:80"
    volumes:
      - ./app/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - test-node-finder
    environment:
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST:-"%"}
      - MYSQL_USER=${MYSQL_USER:-admin}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-node-finder}
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/mysql/data/:/docker-entrypoint-initdb.d/
    ports:
      - 3307:3306
networks:
  test-node-finder:
