version: "3.2"
services:
  php:
    build: "./docker/php/"
    networks:
      - test-node-finder
    volumes:
      - ./app/:/var/www/html/
  apache:
    build: "./docker/apache/"
    depends_on:
      - php
      - mysql
    networks:
      - test-node-finder
    ports:
      - "8080:80"
    volumes:
      - ./app/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - test-node-finder
    environment:
      - MYSQL_ROOT_HOST="%"
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=node-finder
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/mysql/data/:/docker-entrypoint-initdb.d/
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - test-node-finder
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
networks:
  test-node-finder:
